// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getFundsHoldings, getFundsList, getInsiderTransactions, getInstitutionsHoldings, getInstitutionsIssuers, getInstitutionsManagers, getProposedSales, getSupplyChainTicker, type Options } from '../sdk.gen';
import type { GetFundsHoldingsData, GetFundsListData, GetFundsListError, GetFundsListResponse, GetInsiderTransactionsData, GetInstitutionsHoldingsData, GetInstitutionsIssuersData, GetInstitutionsManagersData, GetProposedSalesData, GetSupplyChainTickerData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getFundsHoldingsQueryKey = (options: Options<GetFundsHoldingsData>) => createQueryKey('getFundsHoldings', options);

/**
 * Fund Holdings
 *
 * Get holdings of a specific fund (Mutual Fund or ETF) using N-PORT filings.
 */
export const getFundsHoldingsOptions = (options: Options<GetFundsHoldingsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFundsHoldings({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getFundsHoldingsQueryKey(options)
    });
};

export const getFundsListQueryKey = (options?: Options<GetFundsListData>) => createQueryKey('getFundsList', options);

/**
 * List Funds
 *
 * Get a list of all available funds, including mutual funds, ETFs, and UITs.
 */
export const getFundsListOptions = (options?: Options<GetFundsListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFundsList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getFundsListQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getFundsListInfiniteQueryKey = (options?: Options<GetFundsListData>): QueryKey<Options<GetFundsListData>> => createQueryKey('getFundsList', options, true);

/**
 * List Funds
 *
 * Get a list of all available funds, including mutual funds, ETFs, and UITs.
 */
export const getFundsListInfiniteOptions = (options?: Options<GetFundsListData>) => {
    return infiniteQueryOptions<GetFundsListResponse, GetFundsListError, InfiniteData<GetFundsListResponse>, QueryKey<Options<GetFundsListData>>, number | null | Pick<QueryKey<Options<GetFundsListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetFundsListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getFundsList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getFundsListInfiniteQueryKey(options)
    });
};

export const getInsiderTransactionsQueryKey = (options?: Options<GetInsiderTransactionsData>) => createQueryKey('getInsiderTransactions', options);

/**
 * List Insider Transactions
 *
 * Get SEC Form 3/4/5 insider transactions. Returns both non-derivative (common stock) and derivative (options, warrants) transactions, enriched with issuer details, insider role, and full ownership position context.
 */
export const getInsiderTransactionsOptions = (options?: Options<GetInsiderTransactionsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getInsiderTransactions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getInsiderTransactionsQueryKey(options)
    });
};

export const getInstitutionsHoldingsQueryKey = (options?: Options<GetInstitutionsHoldingsData>) => createQueryKey('getInstitutionsHoldings', options);

/**
 * Detailed Institutional Holdings
 *
 * Detailed holdings analysis, position-level queries, investor-issuer relationship mapping.
 */
export const getInstitutionsHoldingsOptions = (options?: Options<GetInstitutionsHoldingsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getInstitutionsHoldings({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getInstitutionsHoldingsQueryKey(options)
    });
};

export const getInstitutionsIssuersQueryKey = (options?: Options<GetInstitutionsIssuersData>) => createQueryKey('getInstitutionsIssuers', options);

/**
 * Issuer-Aggregated Holdings
 *
 * Issuer-level aggregation (total institutional holders, aggregate value per ticker per quarter).
 */
export const getInstitutionsIssuersOptions = (options?: Options<GetInstitutionsIssuersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getInstitutionsIssuers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getInstitutionsIssuersQueryKey(options)
    });
};

export const getInstitutionsManagersQueryKey = (options?: Options<GetInstitutionsManagersData>) => createQueryKey('getInstitutionsManagers', options);

/**
 * Manager-Aggregated Holdings
 *
 * Manager/Investor-level aggregation (total holdings value, position count per investor per quarter).
 */
export const getInstitutionsManagersOptions = (options?: Options<GetInstitutionsManagersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getInstitutionsManagers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getInstitutionsManagersQueryKey(options)
    });
};

export const getProposedSalesQueryKey = (options?: Options<GetProposedSalesData>) => createQueryKey('getProposedSales', options);

/**
 * List Proposed Sales (Form 144)
 *
 * Get SEC Form 144 proposed sale notices. This captures intentions to sell restricted or control securities by corporate insiders, providing early signals of potential selling pressure. All entries are point-in-time resolved for amendments.
 */
export const getProposedSalesOptions = (options?: Options<GetProposedSalesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getProposedSales({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getProposedSalesQueryKey(options)
    });
};

export const getSupplyChainTickerQueryKey = (options: Options<GetSupplyChainTickerData>) => createQueryKey('getSupplyChainTicker', options);

/**
 * Supply Chain Relationships
 *
 * Returns supply chain relationships for a company extracted from SEC annual filings. Includes suppliers, customers, and partners. Competitor relationships are excluded by default — use include_competitors=true to opt in.
 */
export const getSupplyChainTickerOptions = (options: Options<GetSupplyChainTickerData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSupplyChainTicker({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSupplyChainTickerQueryKey(options)
    });
};
