// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetFundsHoldingsData, GetFundsHoldingsErrors, GetFundsHoldingsResponses, GetFundsListData, GetFundsListErrors, GetFundsListResponses, GetInsiderTransactionsData, GetInsiderTransactionsErrors, GetInsiderTransactionsResponses, GetInstitutionsHoldingsData, GetInstitutionsHoldingsErrors, GetInstitutionsHoldingsResponses, GetInstitutionsIssuersData, GetInstitutionsIssuersErrors, GetInstitutionsIssuersResponses, GetInstitutionsManagersData, GetInstitutionsManagersErrors, GetInstitutionsManagersResponses, GetProposedSalesData, GetProposedSalesErrors, GetProposedSalesResponses, GetSupplyChainTickerData, GetSupplyChainTickerErrors, GetSupplyChainTickerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Fund Holdings
 *
 * Get holdings of a specific fund (Mutual Fund or ETF) using N-PORT filings.
 */
export const getFundsHoldings = <ThrowOnError extends boolean = false>(options: Options<GetFundsHoldingsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetFundsHoldingsResponses, GetFundsHoldingsErrors, ThrowOnError>({
        url: '/funds/holdings',
        ...options
    });
};

/**
 * List Funds
 *
 * Get a list of all available funds, including mutual funds, ETFs, and UITs.
 */
export const getFundsList = <ThrowOnError extends boolean = false>(options?: Options<GetFundsListData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFundsListResponses, GetFundsListErrors, ThrowOnError>({
        url: '/funds/list',
        ...options
    });
};

/**
 * List Insider Transactions
 *
 * Get SEC Form 3/4/5 insider transactions. Returns both non-derivative (common stock) and derivative (options, warrants) transactions, enriched with issuer details, insider role, and full ownership position context.
 */
export const getInsiderTransactions = <ThrowOnError extends boolean = false>(options?: Options<GetInsiderTransactionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetInsiderTransactionsResponses, GetInsiderTransactionsErrors, ThrowOnError>({
        url: '/insider-transactions',
        ...options
    });
};

/**
 * Detailed Institutional Holdings
 *
 * Detailed holdings analysis, position-level queries, investor-issuer relationship mapping.
 */
export const getInstitutionsHoldings = <ThrowOnError extends boolean = false>(options?: Options<GetInstitutionsHoldingsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetInstitutionsHoldingsResponses, GetInstitutionsHoldingsErrors, ThrowOnError>({
        url: '/institutions/holdings',
        ...options
    });
};

/**
 * Issuer-Aggregated Holdings
 *
 * Issuer-level aggregation (total institutional holders, aggregate value per ticker per quarter).
 */
export const getInstitutionsIssuers = <ThrowOnError extends boolean = false>(options?: Options<GetInstitutionsIssuersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetInstitutionsIssuersResponses, GetInstitutionsIssuersErrors, ThrowOnError>({
        url: '/institutions/issuers',
        ...options
    });
};

/**
 * Manager-Aggregated Holdings
 *
 * Manager/Investor-level aggregation (total holdings value, position count per investor per quarter).
 */
export const getInstitutionsManagers = <ThrowOnError extends boolean = false>(options?: Options<GetInstitutionsManagersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetInstitutionsManagersResponses, GetInstitutionsManagersErrors, ThrowOnError>({
        url: '/institutions/managers',
        ...options
    });
};

/**
 * List Proposed Sales (Form 144)
 *
 * Get SEC Form 144 proposed sale notices. This captures intentions to sell restricted or control securities by corporate insiders, providing early signals of potential selling pressure. All entries are point-in-time resolved for amendments.
 */
export const getProposedSales = <ThrowOnError extends boolean = false>(options?: Options<GetProposedSalesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetProposedSalesResponses, GetProposedSalesErrors, ThrowOnError>({
        url: '/proposed-sales',
        ...options
    });
};

/**
 * Supply Chain Relationships
 *
 * Returns supply chain relationships for a company extracted from SEC annual filings. Includes suppliers, customers, and partners. Competitor relationships are excluded by default — use include_competitors=true to opt in.
 */
export const getSupplyChainTicker = <ThrowOnError extends boolean = false>(options: Options<GetSupplyChainTickerData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSupplyChainTickerResponses, GetSupplyChainTickerErrors, ThrowOnError>({
        url: '/supply-chain/:ticker',
        ...options
    });
};
