// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetFundsHoldingsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Fund ticker symbol (e.g., VTSAX)
         */
        symbol: string;
        /**
         * Max holdings to return (default 1000, max 10000)
         */
        limit?: number | null;
    };
    url: '/funds/holdings';
};

export type GetFundsHoldingsErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Fund not found
     */
    404: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'FUND_NOT_FOUND';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetFundsHoldingsError = GetFundsHoldingsErrors[keyof GetFundsHoldingsErrors];

export type GetFundsHoldingsResponses = {
    /**
     * Returns fund holdings
     */
    200: {
        count: number;
        holdings: Array<{
            /**
             * Type of asset (e.g., Equity, Debt)
             */
            assetType: string;
            /**
             * Name of the issuer
             */
            name: string;
            /**
             * Percentage of the fund's total value
             */
            percent: number | null;
            /**
             * Number of shares held
             */
            share: number | null;
            /**
             * Ticker symbol of the holding
             */
            symbol: string | null;
            /**
             * USD value of the position
             */
            value: number | null;
        }>;
        numberOfHoldings: number;
        success: boolean;
        symbol: string;
    };
};

export type GetFundsHoldingsResponse = GetFundsHoldingsResponses[keyof GetFundsHoldingsResponses];

export type GetFundsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max results to return (default 1000, max 5000)
         */
        limit?: number | null;
        /**
         * Offset for pagination
         */
        offset?: number | null;
    };
    url: '/funds/list';
};

export type GetFundsListErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetFundsListError = GetFundsListErrors[keyof GetFundsListErrors];

export type GetFundsListResponses = {
    /**
     * Returns list of funds
     */
    200: {
        count: number;
        funds: Array<{
            /**
             * SEC Central Index Key
             */
            cik: number;
            /**
             * SEC class ID (for mutual funds/ETFs)
             */
            class_id: string | null;
            /**
             * Type of entity (e.g., investment)
             */
            entity_type: string | null;
            /**
             * Listing exchange (standard tickers only)
             */
            exchange: string | null;
            /**
             * Legal name of the entity
             */
            name: string;
            /**
             * SEC series ID (for mutual funds/ETFs)
             */
            series_id: string | null;
            /**
             * Fund ticker symbol
             */
            symbol: string;
        }>;
        success: boolean;
    };
};

export type GetFundsListResponse = GetFundsListResponses[keyof GetFundsListResponses];

export type GetInsiderTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Stock ticker symbol (e.g., AAPL, TSLA)
         */
        ticker?: string;
        /**
         * Partial owner name match, case-insensitive (e.g., 'Cook Timothy')
         */
        ownername?: string;
        /**
         * Filing date >= YYYY-MM-DD
         */
        filingdate_gte?: string;
        /**
         * Filing date <= YYYY-MM-DD
         */
        filingdate_lte?: string;
        /**
         * Transaction code: P=Purchase, S=Sale, M=Exercise, A=Award, F=Tax withholding, G=Gift
         */
        transactioncode?: string;
        /**
         * Min absolute transaction value in USD
         */
        transactionvalue_gte?: number | null;
        /**
         * Max absolute transaction value in USD
         */
        transactionvalue_lte?: number | null;
        /**
         * Security type: N=Non-derivative, D=Derivative
         */
        securityadcode?: 'N' | 'D';
        /**
         * Form type (3, 4, 5)
         */
        formtype?: string;
        /**
         * Filter by officer status
         */
        isofficer?: string;
        /**
         * Filter by director status
         */
        isdirector?: string;
        /**
         * Filter by 10%+ ownership status
         */
        istenpercentowner?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
    };
    url: '/insider-transactions';
};

export type GetInsiderTransactionsErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Active subscription required
     */
    403: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'SUBSCRIPTION_REQUIRED';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInsiderTransactionsError = GetInsiderTransactionsErrors[keyof GetInsiderTransactionsErrors];

export type GetInsiderTransactionsResponses = {
    /**
     * Returns a list of insider transactions
     */
    200: {
        count: number;
        success: boolean;
        transactions: Array<{
            acquisitionOrDisposition: string | null;
            directOrIndirect: string | null;
            exercisePrice: number | null;
            expirationDate: string | null;
            filingDate: string | null;
            formType: string | null;
            isDirector: boolean;
            isOfficer: boolean;
            isOther: boolean;
            isTenPercentOwner: boolean;
            issuerCik: string | null;
            issuerName: string | null;
            natureOfOwnership: string | null;
            netShares: number | null;
            officerTitle: string | null;
            otherRelationship: string | null;
            ownerCik: string | null;
            ownerName: string | null;
            periodOfReport: string | null;
            secUrl: string | null;
            securityAdCode: string;
            securityTitle: string | null;
            sharesOwnedBeforeTransaction: number | null;
            sharesOwnedFollowingTransaction: number | null;
            ticker: string | null;
            transactionCode: string | null;
            transactionDate: string | null;
            transactionPricePerShare: number | null;
            transactionShares: number | null;
            transactionValue: number | null;
        }>;
    };
};

export type GetInsiderTransactionsResponse = GetInsiderTransactionsResponses[keyof GetInsiderTransactionsResponses];

export type GetInstitutionsHoldingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by quarter-end date (YYYY-MM-DD)
         */
        calendardate?: string;
        /**
         * Filter date range (start) YYYY-MM-DD
         */
        calendardate_gte?: string;
        /**
         * Filter date range (end) YYYY-MM-DD
         */
        calendardate_lte?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
        /**
         * Filter by issuer ticker
         */
        ticker?: string;
        /**
         * Filter by investor name
         */
        investorname?: string;
        /**
         * Filter by security type code (SHR, FND, CLL, PUT, WNT, DBT, PRF, UND). Comma-separated.
         */
        securitytype?: string;
    };
    url: '/institutions/holdings';
};

export type GetInstitutionsHoldingsErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInstitutionsHoldingsError = GetInstitutionsHoldingsErrors[keyof GetInstitutionsHoldingsErrors];

export type GetInstitutionsHoldingsResponses = {
    /**
     * Returns detailed holding positions
     */
    200: {
        count: number;
        holdings: Array<{
            /**
             * Quarter-end reporting date (YYYY-MM-DD)
             */
            calendardate: string | null;
            /**
             * Full legal name of institutional investor
             */
            investorname: string | null;
            /**
             * Security classification code (e.g., SHR, FND, CLL, PUT, WNT, DBT, PRF, UND)
             */
            securitytype: string | null;
            /**
             * Issuer ticker symbol
             */
            ticker: string | null;
            /**
             * Quantity of securities (shares/contracts)
             */
            units: number | null;
            /**
             * Total USD market value
             */
            value: number | null;
        }>;
        success: boolean;
    };
};

export type GetInstitutionsHoldingsResponse = GetInstitutionsHoldingsResponses[keyof GetInstitutionsHoldingsResponses];

export type GetInstitutionsIssuersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by quarter-end date (YYYY-MM-DD)
         */
        calendardate?: string;
        /**
         * Filter date range (start) YYYY-MM-DD
         */
        calendardate_gte?: string;
        /**
         * Filter date range (end) YYYY-MM-DD
         */
        calendardate_lte?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
        /**
         * Filter by issuer ticker
         */
        ticker?: string;
    };
    url: '/institutions/issuers';
};

export type GetInstitutionsIssuersErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInstitutionsIssuersError = GetInstitutionsIssuersErrors[keyof GetInstitutionsIssuersErrors];

export type GetInstitutionsIssuersResponses = {
    /**
     * Returns issuer-aggregated totals
     */
    200: {
        count: number;
        issuers: Array<{
            /**
             * Quarter-end reporting date (YYYY-MM-DD)
             */
            calendardate: string | null;
            /**
             * Count of distinct institutional investors holding this issuer
             */
            shrholders: number | null;
            /**
             * Issuer ticker symbol
             */
            ticker: string | null;
            /**
             * Aggregate units across all investors
             */
            total_units: number | null;
            /**
             * Aggregate USD value across all investors
             */
            total_value: number | null;
        }>;
        success: boolean;
    };
};

export type GetInstitutionsIssuersResponse = GetInstitutionsIssuersResponses[keyof GetInstitutionsIssuersResponses];

export type GetInstitutionsManagersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by quarter-end date (YYYY-MM-DD)
         */
        calendardate?: string;
        /**
         * Filter date range (start) YYYY-MM-DD
         */
        calendardate_gte?: string;
        /**
         * Filter date range (end) YYYY-MM-DD
         */
        calendardate_lte?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
        /**
         * Filter by investor name
         */
        investorname?: string;
    };
    url: '/institutions/managers';
};

export type GetInstitutionsManagersErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInstitutionsManagersError = GetInstitutionsManagersErrors[keyof GetInstitutionsManagersErrors];

export type GetInstitutionsManagersResponses = {
    /**
     * Returns manager-aggregated totals
     */
    200: {
        count: number;
        managers: Array<{
            /**
             * Quarter-end reporting date (YYYY-MM-DD)
             */
            calendardate: string | null;
            /**
             * Institutional investor legal name
             */
            investorname: string | null;
            /**
             * Count of distinct issuer tickers held by this investor
             */
            shrholdings: number | null;
            /**
             * Aggregate units across all holdings
             */
            total_units: number | null;
            /**
             * Aggregate USD value of all holdings
             */
            total_value: number | null;
        }>;
        success: boolean;
    };
};

export type GetInstitutionsManagersResponse = GetInstitutionsManagersResponses[keyof GetInstitutionsManagersResponses];

export type GetProposedSalesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Stock ticker symbol (e.g., TSLA, NVDA)
         */
        ticker?: string;
        /**
         * Partial seller name match, case-insensitive
         */
        seller?: string;
        /**
         * Filing date >= YYYY-MM-DD
         */
        date_gte?: string;
        /**
         * Filing date <= YYYY-MM-DD
         */
        date_lte?: string;
        /**
         * Min aggregate market value of proposed sale
         */
        min_value?: number | null;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
    };
    url: '/proposed-sales';
};

export type GetProposedSalesErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
    /**
     * Active subscription required
     */
    403: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
    /**
     * Rate limit exceeded
     */
    429: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
    /**
     * Server error
     */
    500: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
};

export type GetProposedSalesError = GetProposedSalesErrors[keyof GetProposedSalesErrors];

export type GetProposedSalesResponses = {
    /**
     * Returns a list of proposed sales
     */
    200: {
        count: number;
        sales: Array<{
            approxSaleDate: string | null;
            broker: string | null;
            filingDate: string | null;
            formType: string | null;
            issuerCik: string | null;
            issuerName: string | null;
            market: string | null;
            noticeDate: string | null;
            secUrl: string | null;
            sellerCik: string | null;
            sellerName: string | null;
            shares: number | null;
            ticker: string | null;
            value: number | null;
        }>;
        success: true;
    };
};

export type GetProposedSalesResponse = GetProposedSalesResponses[keyof GetProposedSalesResponses];

export type GetSupplyChainTickerData = {
    body?: never;
    path: {
        /**
         * Stock ticker symbol (e.g., AAPL, NVDA)
         */
        ticker: string;
    };
    query?: {
        /**
         * 'outgoing': only relationships the queried company filed themselves. 'incoming': only relationships where another company mentioned the queried company. 'both' (default): all.
         */
        direction?: 'incoming' | 'outgoing' | 'both';
        /**
         * Hide 'Customer A/B/C' placeholder nodes (default true)
         */
        exclude_anonymized?: string;
        /**
         * Include competitor relationships (default false). Competitor data tends to be broad — opt in if needed.
         */
        include_competitors?: string;
    };
    url: '/supply-chain/:ticker';
};

export type GetSupplyChainTickerErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR';
    };
    /**
     * Active subscription required
     */
    403: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR';
    };
    /**
     * Company not found for ticker
     */
    404: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'COMPANY_NOT_FOUND';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR';
    };
};

export type GetSupplyChainTickerError = GetSupplyChainTickerErrors[keyof GetSupplyChainTickerErrors];

export type GetSupplyChainTickerResponses = {
    /**
     * Returns supply chain relationships for the company
     */
    200: {
        /**
         * Total number of relationships returned
         */
        count: number;
        /**
         * Most recent filing date among the returned relationships (YYYY-MM-DD). Useful for assessing data freshness.
         */
        latestFilingDate: string | null;
        relationships: Array<{
            /**
             * Short description of the relationship drawn directly from the filing (5–15 words)
             */
            context: string | null;
            /**
             * 'outgoing' means the queried company filed this relationship (they mentioned the other company). 'incoming' means another company's filing mentioned the queried company.
             */
            direction: 'incoming' | 'outgoing';
            /**
             * Date of the SEC filing this relationship was extracted from (YYYY-MM-DD)
             */
            filingDate: string | null;
            /**
             * Type of relationship. One of: supplier, customer, partner, partner_manufacturing, partner_joint_venture, partner_equity, partner_research, partner_distribution, competitor (opt-in).
             */
            relationshipType: string | null;
            /**
             * For customer relationships only: the percentage of the filing company's revenue this customer represents. Null for all other relationship types.
             */
            revenuePercentage: number | null;
            /**
             * Direct link to the SEC EDGAR filing index page this relationship was sourced from
             */
            secUrl: string | null;
            /**
             * Name of the filing company (the one that mentioned the relationship in their SEC filing)
             */
            sourceName: string | null;
            /**
             * Ticker symbol of the filing company. Null if unlisted or private.
             */
            sourceSymbol: string | null;
            /**
             * Name of the mentioned company
             */
            targetName: string | null;
            /**
             * Ticker symbol of the mentioned company. Null if unlisted or private.
             */
            targetSymbol: string | null;
        }>;
        success: true;
        /**
         * The queried ticker symbol, uppercased
         */
        ticker: string;
    };
};

export type GetSupplyChainTickerResponse = GetSupplyChainTickerResponses[keyof GetSupplyChainTickerResponses];
