// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetInsiderTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Stock ticker symbol (e.g., AAPL, TSLA)
         */
        ticker?: string;
        /**
         * Partial owner name match, case-insensitive (e.g., 'Cook Timothy')
         */
        ownername?: string;
        /**
         * Filing date >= YYYY-MM-DD
         */
        filingdate_gte?: string;
        /**
         * Filing date <= YYYY-MM-DD
         */
        filingdate_lte?: string;
        /**
         * Transaction code: P=Purchase, S=Sale, M=Exercise, A=Award, F=Tax withholding, G=Gift
         */
        transactioncode?: string;
        /**
         * Min absolute transaction value in USD
         */
        transactionvalue_gte?: number | null;
        /**
         * Max absolute transaction value in USD
         */
        transactionvalue_lte?: number | null;
        /**
         * Security type: N=Non-derivative, D=Derivative
         */
        securityadcode?: 'N' | 'D';
        /**
         * Form type (3, 4, 5)
         */
        formtype?: string;
        /**
         * Filter by officer status
         */
        isofficer?: string;
        /**
         * Filter by director status
         */
        isdirector?: string;
        /**
         * Filter by 10%+ ownership status
         */
        istenpercentowner?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
    };
    url: '/insider-transactions';
};

export type GetInsiderTransactionsErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Active subscription required
     */
    403: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'SUBSCRIPTION_REQUIRED';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInsiderTransactionsError = GetInsiderTransactionsErrors[keyof GetInsiderTransactionsErrors];

export type GetInsiderTransactionsResponses = {
    /**
     * Returns a list of insider transactions
     */
    200: {
        count: number;
        success: boolean;
        transactions: Array<{
            acquisitionOrDisposition: string | null;
            directOrIndirect: string | null;
            exercisePrice: number | null;
            expirationDate: string | null;
            filingDate: string | null;
            formType: string | null;
            isDirector: boolean;
            isOfficer: boolean;
            isOther: boolean;
            isTenPercentOwner: boolean;
            issuerCik: string | null;
            issuerName: string | null;
            natureOfOwnership: string | null;
            netShares: number | null;
            officerTitle: string | null;
            otherRelationship: string | null;
            ownerCik: string | null;
            ownerName: string | null;
            periodOfReport: string | null;
            secUrl: string | null;
            securityAdCode: string;
            securityTitle: string | null;
            sharesOwnedBeforeTransaction: number | null;
            sharesOwnedFollowingTransaction: number | null;
            ticker: string | null;
            transactionCode: string | null;
            transactionDate: string | null;
            transactionPricePerShare: number | null;
            transactionShares: number | null;
            transactionValue: number | null;
        }>;
    };
};

export type GetInsiderTransactionsResponse = GetInsiderTransactionsResponses[keyof GetInsiderTransactionsResponses];

export type GetInstitutionsHoldingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by quarter-end date (YYYY-MM-DD)
         */
        calendardate?: string;
        /**
         * Filter date range (start) YYYY-MM-DD
         */
        calendardate_gte?: string;
        /**
         * Filter date range (end) YYYY-MM-DD
         */
        calendardate_lte?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
        /**
         * Filter by issuer ticker
         */
        ticker?: string;
        /**
         * Filter by investor name
         */
        investorname?: string;
        /**
         * Filter by security type code (SHR, FND, CLL, PUT, WNT, DBT, PRF, UND). Comma-separated.
         */
        securitytype?: string;
    };
    url: '/institutions/holdings';
};

export type GetInstitutionsHoldingsErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInstitutionsHoldingsError = GetInstitutionsHoldingsErrors[keyof GetInstitutionsHoldingsErrors];

export type GetInstitutionsHoldingsResponses = {
    /**
     * Returns detailed holding positions
     */
    200: {
        count: number;
        holdings: Array<{
            /**
             * Quarter-end reporting date (YYYY-MM-DD)
             */
            calendardate: string | null;
            /**
             * Full legal name of institutional investor
             */
            investorname: string | null;
            /**
             * Security classification code (e.g., SHR, FND, CLL, PUT, WNT, DBT, PRF, UND)
             */
            securitytype: string | null;
            /**
             * Issuer ticker symbol
             */
            ticker: string | null;
            /**
             * Quantity of securities (shares/contracts)
             */
            units: number | null;
            /**
             * Total USD market value
             */
            value: number | null;
        }>;
        success: boolean;
    };
};

export type GetInstitutionsHoldingsResponse = GetInstitutionsHoldingsResponses[keyof GetInstitutionsHoldingsResponses];

export type GetInstitutionsIssuersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by quarter-end date (YYYY-MM-DD)
         */
        calendardate?: string;
        /**
         * Filter date range (start) YYYY-MM-DD
         */
        calendardate_gte?: string;
        /**
         * Filter date range (end) YYYY-MM-DD
         */
        calendardate_lte?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
        /**
         * Filter by issuer ticker
         */
        ticker?: string;
    };
    url: '/institutions/issuers';
};

export type GetInstitutionsIssuersErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInstitutionsIssuersError = GetInstitutionsIssuersErrors[keyof GetInstitutionsIssuersErrors];

export type GetInstitutionsIssuersResponses = {
    /**
     * Returns issuer-aggregated totals
     */
    200: {
        count: number;
        issuers: Array<{
            /**
             * Quarter-end reporting date (YYYY-MM-DD)
             */
            calendardate: string | null;
            /**
             * Count of distinct institutional investors holding this issuer
             */
            shrholders: number | null;
            /**
             * Issuer ticker symbol
             */
            ticker: string | null;
            /**
             * Aggregate units across all investors
             */
            total_units: number | null;
            /**
             * Aggregate USD value across all investors
             */
            total_value: number | null;
        }>;
        success: boolean;
    };
};

export type GetInstitutionsIssuersResponse = GetInstitutionsIssuersResponses[keyof GetInstitutionsIssuersResponses];

export type GetInstitutionsManagersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by quarter-end date (YYYY-MM-DD)
         */
        calendardate?: string;
        /**
         * Filter date range (start) YYYY-MM-DD
         */
        calendardate_gte?: string;
        /**
         * Filter date range (end) YYYY-MM-DD
         */
        calendardate_lte?: string;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
        /**
         * Filter by investor name
         */
        investorname?: string;
    };
    url: '/institutions/managers';
};

export type GetInstitutionsManagersErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'INVALID_API_KEY';
    };
    /**
     * Rate limit exceeded
     */
    429: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'RATE_LIMIT_EXCEEDED';
    };
    /**
     * Server error
     */
    500: {
        details?: unknown;
        error: true;
        message?: string;
        type: 'UNKNOWN_ERROR' | 'DATABASE_NOT_CONFIGURED';
    };
};

export type GetInstitutionsManagersError = GetInstitutionsManagersErrors[keyof GetInstitutionsManagersErrors];

export type GetInstitutionsManagersResponses = {
    /**
     * Returns manager-aggregated totals
     */
    200: {
        count: number;
        managers: Array<{
            /**
             * Quarter-end reporting date (YYYY-MM-DD)
             */
            calendardate: string | null;
            /**
             * Institutional investor legal name
             */
            investorname: string | null;
            /**
             * Count of distinct issuer tickers held by this investor
             */
            shrholdings: number | null;
            /**
             * Aggregate units across all holdings
             */
            total_units: number | null;
            /**
             * Aggregate USD value of all holdings
             */
            total_value: number | null;
        }>;
        success: boolean;
    };
};

export type GetInstitutionsManagersResponse = GetInstitutionsManagersResponses[keyof GetInstitutionsManagersResponses];

export type GetProposedSalesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Stock ticker symbol (e.g., TSLA, NVDA)
         */
        ticker?: string;
        /**
         * Partial seller name match, case-insensitive
         */
        seller?: string;
        /**
         * Filing date >= YYYY-MM-DD
         */
        date_gte?: string;
        /**
         * Filing date <= YYYY-MM-DD
         */
        date_lte?: string;
        /**
         * Min aggregate market value of proposed sale
         */
        min_value?: number | null;
        /**
         * Max rows to return (default 1000, max 10000)
         */
        limit?: number | null;
    };
    url: '/proposed-sales';
};

export type GetProposedSalesErrors = {
    /**
     * Invalid or missing API key
     */
    401: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
    /**
     * Active subscription required
     */
    403: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
    /**
     * Rate limit exceeded
     */
    429: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
    /**
     * Server error
     */
    500: {
        error: {
            code: string;
            message: string;
        };
        success: false;
    };
};

export type GetProposedSalesError = GetProposedSalesErrors[keyof GetProposedSalesErrors];

export type GetProposedSalesResponses = {
    /**
     * Returns a list of proposed sales
     */
    200: {
        count: number;
        sales: Array<{
            approxSaleDate: string | null;
            broker: string | null;
            filingDate: string | null;
            formType: string | null;
            issuerCik: string | null;
            issuerName: string | null;
            market: string | null;
            noticeDate: string | null;
            secUrl: string | null;
            sellerCik: string | null;
            sellerName: string | null;
            shares: number | null;
            ticker: string | null;
            value: number | null;
        }>;
        success: true;
    };
};

export type GetProposedSalesResponse = GetProposedSalesResponses[keyof GetProposedSalesResponses];
